"""Canonical domain enums — DB stores UPPER_SNAKE strings."""

from __future__ import annotations

# Roles
ROLE_ANALYST = "ANALYST"
ROLE_COMPLIANCE_LEAD = "COMPLIANCE_LEAD"

# Alert status
ALERT_OPEN = "OPEN"
ALERT_IN_PROGRESS = "IN_PROGRESS"
ALERT_PENDING_OFFICER_REVIEW = "PENDING_OFFICER_REVIEW"
ALERT_CLOSED = "CLOSED"

OPEN_WORK_STATUSES = frozenset({ALERT_OPEN, ALERT_IN_PROGRESS, ALERT_PENDING_OFFICER_REVIEW})

# Disposition (on close)
DISPOSITION_FALSE_POSITIVE = "FALSE_POSITIVE"
DISPOSITION_NO_ACTION = "NO_ACTION_REQUIRED"
DISPOSITION_CLEARED_MONITORING = "CLEARED_WITH_MONITORING"
DISPOSITION_ESCALATED_REGULATOR = "ESCALATED_TO_REGULATOR"

VALID_DISPOSITIONS = frozenset({
    DISPOSITION_FALSE_POSITIVE,
    DISPOSITION_NO_ACTION,
    DISPOSITION_CLEARED_MONITORING,
    DISPOSITION_ESCALATED_REGULATOR,
})

# Investigation
VERDICT_ESCALATE = "ESCALATE"
VERDICT_MONITOR = "MONITOR"
VERDICT_DISMISS = "DISMISS"

REVIEW_AI_COMPLETE = "AI_COMPLETE"
REVIEW_ANALYST_APPROVED = "ANALYST_APPROVED"
REVIEW_OFFICER_APPROVED = "OFFICER_APPROVED"

APPROVED_REVIEW_STATUSES = frozenset({REVIEW_ANALYST_APPROVED, REVIEW_OFFICER_APPROVED})

# Demo accounts (email → role override on provision)
DEMO_USER_ROLES: dict[str, str] = {
    "analyst@demo.sentinel": ROLE_ANALYST,
    "officer@demo.sentinel": ROLE_COMPLIANCE_LEAD,
}

DEMO_DISPLAY_NAMES: dict[str, str] = {
    "analyst@demo.sentinel": "Demo Analyst",
    "officer@demo.sentinel": "Demo Officer",
}

STALE_HOURS = 24
